# Generated by Django 4.0.4 on 2022-06-02 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_product_issold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=100)),
                ('buyerId', models.CharField(max_length=100)),
                ('sellerId', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('transactionId', models.CharField(max_length=100)),
            ],
        ),
    ]
