# Generated by Django 4.0.4 on 2022-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_messages_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
