# Generated by Django 4.0.4 on 2022-06-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_events_alter_product_issold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='room',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='sender',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='text',
        ),
    ]
