# Generated by Django 4.0.4 on 2022-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_room_messages_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='recovery_code',
            field=models.CharField(default=53746374976213, max_length=100),
            preserve_default=False,
        ),
    ]
