# Generated by Django 4.0.4 on 2022-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_users_isbanned_users_recovery_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='username',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isBanned',
        ),
        migrations.RemoveField(
            model_name='users',
            name='recovery_code',
        ),
        migrations.AddField(
            model_name='messages',
            name='text',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
