# Generated by Django 4.0.4 on 2022-06-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_message_messages_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='room',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='sender',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='text',
        ),
        migrations.AddField(
            model_name='users',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='recovery_code',
            field=models.CharField(default=12131231247667345, max_length=100),
            preserve_default=False,
        ),
    ]
