# Generated by Django 4.0.4 on 2022-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_room_messages_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='room',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
